### ISSUE TITLE
Throw error if invalid character is passed

### ISSUE THREAD

**Issue by kuon** [carlosafonso/php-base24#1]
I suggest your throw an explicit error in the decode function if the `$idx` is null/not found when invalid characters are passed to the decoder. (`$s` not present in `decodeMap`)

https://github.com/carlosafonso/php-base24/blob/4692d3d982ac45c92c83f666cf8324061db8582e/src/Encoder.php#L106

**Comment by carlosafonso** [comment]
Fixed, thanks!
